# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='position_x',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='position_y',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
