# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkt', '0002_auto_20171201_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkttype',
            name='tiefkuel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
