# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkt', '0003_produkttype_tiefkuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkttype',
            old_name='tiefkuel',
            new_name='tiefkuehl',
        ),
    ]
